name: backend Actions

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Docker backend, db
      run: |
        cd /home/server-admin/services/reservac/backend/
        git pull https://github.com/MAC-USB/reservac-backend.git
        docker compose up --build -d
        curl -I reservac.ac.labf.usb.ve/api/check
        docker logs backend_reserva_cont | tail -n 100
