name: backend Actions

on:
  push:
    branches: [ "master" ]
  
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Docker backend, db
      run: |
        cd ~/services/reservac/backend/
        git pull https://github.com/Etvulk/reservac-backend.git
        docker compose up --build -d
